/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  logo: require('App/Assets/Images/Artery_Pay_Icon.png'),
  activityNavIcon: require('App/Assets/Images/Activity_Nav_Icon.png'),
  amountIcon: require('App/Assets/Images/Amount_Icon.png'),
  backArrowIcon: require('App/Assets/Images/Back_Arrow_Icon.png'),
  checkmarkIcon: require('App/Assets/Images/Checkmark_Icon.png'),
  clearIcon: require('App/Assets/Images/Clear_Icon.png'),
  closeAccordionIcon: require('App/Assets/Images/Close_Accordion_Icon.png'),
  closeIcon: require('App/Assets/Images/Close_Icon.png'),
  codeIcon: require('App/Assets/Images/Code_Icon.png'),
  confirmationIcon: require('App/Assets/Images/Confirmation_Icon.png'),
  contactIcon: require('App/Assets/Images/Contact_Icon.png'),
  createPasswordIcon: require('App/Assets/Images/Create_Password_Icon.png'),
  dashboardNavIcon: require('App/Assets/Images/Dashboard_Nav_Icon.png'),
  forwardArrowIcon: require('App/Assets/Images/Forward_Arrow_Icon.png'),
  goldenStateCannaIcon: require('App/Assets/Images/Golden_State_Canna_Icon.png'),
  hamburgerMenuIcon: require('App/Assets/Images/Hamburger_Menu_Icon.png'),
  IDIcon: require('App/Assets/Images/ID_Icon.png'),
  inyoIcon: require('App/Assets/Images/Inyo_Icon.png'),
  linkBankAccountIcon: require('App/Assets/Images/Link_Bank_Account_Icon.png'),
  locationIcon: require('App/Assets/Images/Location_Icon.png'),
  magnifyingGlassIcon: require('App/Assets/Images/Magnifying_Glass_Icon.png'),
  magnifyingGlassInactiveIcon: require('App/Assets/Images/Magnifying_Glass_Icon_-_Inactive.png'),
  openAccordionIcon: require('App/Assets/Images/Open_Accordion_Icon.png'),
  philIcon: require('App/Assets/Images/Phil_Icon.png'),
  photoIcon: require('App/Assets/Images/Photo_Icon.png'),
  ponderIcon: require('App/Assets/Images/Ponder_Icon.png'),
  recipientIcon: require('App/Assets/Images/Recipient_Icon.png'),
  requestMoneyNavIcon: require('App/Assets/Images/Request_Money_Nav_Icon.png'),
  scanMeNavIcon: require('App/Assets/Images/Scan_Me_Nav_Icon.png'),
  scanQrIcon: require('App/Assets/Images/Scan_QR_Icon.png'),
  sendMoneyIcon: require('App/Assets/Images/Send_Money_Icon.png'),
  sendMoneyNavIcon: require('App/Assets/Images/Send_Money_Nav_Icon.png'),
  settingsIcon: require('App/Assets/Images/Settings_Icon.png'),
  signInIcon: require('App/Assets/Images/Sign_In_Icon.png'),
  stephenIcon: require('App/Assets/Images/Stephen_Icon.png'),
  wellsIcon: require('App/Assets/Images/Wells_Icon.png'),
  illustration: require('App/Assets/Images/Illustration.png'),
};
